/*
 * This file was generated automatically by ExtUtils::ParseXS version 3.18 from the
 * contents of WiringPi.xs. Do not edit this file, edit WiringPi.xs instead.
 *
 *    ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "WiringPi.xs"
#define PERL_NO_GET_CONTEXT
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#include "ppport.h"
#include <wiringPi.h>
#include <wiringPiI2C.h>
#include <wiringSerial.h>
#include <lcd.h>

#line 22 "WiringPi.c"
#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#ifndef dVAR
#  define dVAR		dNOOP
#endif


/* This stuff is not part of the API! You have been warned. */
#ifndef PERL_VERSION_DECIMAL
#  define PERL_VERSION_DECIMAL(r,v,s) (r*1000000 + v*1000 + s)
#endif
#ifndef PERL_DECIMAL_VERSION
#  define PERL_DECIMAL_VERSION \
	  PERL_VERSION_DECIMAL(PERL_REVISION,PERL_VERSION,PERL_SUBVERSION)
#endif
#ifndef PERL_VERSION_GE
#  define PERL_VERSION_GE(r,v,s) \
	  (PERL_DECIMAL_VERSION >= PERL_VERSION_DECIMAL(r,v,s))
#endif
#ifndef PERL_VERSION_LE
#  define PERL_VERSION_LE(r,v,s) \
	  (PERL_DECIMAL_VERSION <= PERL_VERSION_DECIMAL(r,v,s))
#endif

/* XS_INTERNAL is the explicit static-linkage variant of the default
 * XS macro.
 *
 * XS_EXTERNAL is the same as XS_INTERNAL except it does not include
 * "STATIC", ie. it exports XSUB symbols. You probably don't want that
 * for anything but the BOOT XSUB.
 *
 * See XSUB.h in core!
 */


/* TODO: This might be compatible further back than 5.10.0. */
#if PERL_VERSION_GE(5, 10, 0) && PERL_VERSION_LE(5, 15, 1)
#  undef XS_EXTERNAL
#  undef XS_INTERNAL
#  if defined(__CYGWIN__) && defined(USE_DYNAMIC_LOADING)
#    define XS_EXTERNAL(name) __declspec(dllexport) XSPROTO(name)
#    define XS_INTERNAL(name) STATIC XSPROTO(name)
#  endif
#  if defined(__SYMBIAN32__)
#    define XS_EXTERNAL(name) EXPORT_C XSPROTO(name)
#    define XS_INTERNAL(name) EXPORT_C STATIC XSPROTO(name)
#  endif
#  ifndef XS_EXTERNAL
#    if defined(HASATTRIBUTE_UNUSED) && !defined(__cplusplus)
#      define XS_EXTERNAL(name) void name(pTHX_ CV* cv __attribute__unused__)
#      define XS_INTERNAL(name) STATIC void name(pTHX_ CV* cv __attribute__unused__)
#    else
#      ifdef __cplusplus
#        define XS_EXTERNAL(name) extern "C" XSPROTO(name)
#        define XS_INTERNAL(name) static XSPROTO(name)
#      else
#        define XS_EXTERNAL(name) XSPROTO(name)
#        define XS_INTERNAL(name) STATIC XSPROTO(name)
#      endif
#    endif
#  endif
#endif

/* perl >= 5.10.0 && perl <= 5.15.1 */


/* The XS_EXTERNAL macro is used for functions that must not be static
 * like the boot XSUB of a module. If perl didn't have an XS_EXTERNAL
 * macro defined, the best we can do is assume XS is the same.
 * Dito for XS_INTERNAL.
 */
#ifndef XS_EXTERNAL
#  define XS_EXTERNAL(name) XS(name)
#endif
#ifndef XS_INTERNAL
#  define XS_INTERNAL(name) XS(name)
#endif

/* Now, finally, after all this mess, we want an ExtUtils::ParseXS
 * internal macro that we're free to redefine for varying linkage due
 * to the EXPORT_XSUB_SYMBOLS XS keyword. This is internal, use
 * XS_EXTERNAL(name) or XS_INTERNAL(name) in your code if you need to!
 */

#undef XS_EUPXS
#if defined(PERL_EUPXS_ALWAYS_EXPORT)
#  define XS_EUPXS(name) XS_EXTERNAL(name)
#else
   /* default to internal */
#  define XS_EUPXS(name) XS_INTERNAL(name)
#endif

#ifndef PERL_ARGS_ASSERT_CROAK_XS_USAGE
#define PERL_ARGS_ASSERT_CROAK_XS_USAGE assert(cv); assert(params)

/* prototype to pass -Wmissing-prototypes */
STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params);

STATIC void
S_croak_xs_usage(pTHX_ const CV *const cv, const char *const params)
{
    const GV *const gv = CvGV(cv);

    PERL_ARGS_ASSERT_CROAK_XS_USAGE;

    if (gv) {
        const char *const gvname = GvNAME(gv);
        const HV *const stash = GvSTASH(gv);
        const char *const hvname = stash ? HvNAME(stash) : NULL;

        if (hvname)
            Perl_croak(aTHX_ "Usage: %s::%s(%s)", hvname, gvname, params);
        else
            Perl_croak(aTHX_ "Usage: %s(%s)", gvname, params);
    } else {
        /* Pants. I don't think that it should be possible to get here. */
        Perl_croak(aTHX_ "Usage: CODE(0x%"UVxf")(%s)", PTR2UV(cv), params);
    }
}
#undef  PERL_ARGS_ASSERT_CROAK_XS_USAGE

#ifdef PERL_IMPLICIT_CONTEXT
#define croak_xs_usage(a,b)    S_croak_xs_usage(aTHX_ a,b)
#else
#define croak_xs_usage        S_croak_xs_usage
#endif

#endif

/* NOTE: the prototype of newXSproto() is different in versions of perls,
 * so we define a portable version of newXSproto()
 */
#ifdef newXS_flags
#define newXSproto_portable(name, c_impl, file, proto) newXS_flags(name, c_impl, file, proto, 0)
#else
#define newXSproto_portable(name, c_impl, file, proto) (PL_Sv=(SV*)newXS(name, c_impl, file), sv_setpv(PL_Sv, proto), (CV*)PL_Sv)
#endif /* !defined(newXS_flags) */

#line 164 "WiringPi.c"

XS_EUPXS(XS_Odroid__WiringPi_lcdHome); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Odroid__WiringPi_lcdHome)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "fd");
    {
	int	fd = (int)SvIV(ST(0))
;

	lcdHome(fd);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Odroid__WiringPi_lcdClear); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Odroid__WiringPi_lcdClear)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "fd");
    {
	int	fd = (int)SvIV(ST(0))
;

	lcdClear(fd);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Odroid__WiringPi_lcdDisplay); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Odroid__WiringPi_lcdDisplay)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "fd, state");
    {
	int	fd = (int)SvIV(ST(0))
;
	int	state = (int)SvIV(ST(1))
;

	lcdDisplay(fd, state);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Odroid__WiringPi_lcdCursor); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Odroid__WiringPi_lcdCursor)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "fd, state");
    {
	int	fd = (int)SvIV(ST(0))
;
	int	state = (int)SvIV(ST(1))
;

	lcdCursor(fd, state);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Odroid__WiringPi_lcdCursorBlink); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Odroid__WiringPi_lcdCursorBlink)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "fd, state");
    {
	int	fd = (int)SvIV(ST(0))
;
	int	state = (int)SvIV(ST(1))
;

	lcdCursorBlink(fd, state);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Odroid__WiringPi_lcdSendCommand); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Odroid__WiringPi_lcdSendCommand)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "fd, command");
    {
	int	fd = (int)SvIV(ST(0))
;
	char	command = (char)*SvPV_nolen(ST(1))
;

	lcdSendCommand(fd, command);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Odroid__WiringPi_lcdPosition); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Odroid__WiringPi_lcdPosition)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "fd, x, y");
    {
	int	fd = (int)SvIV(ST(0))
;
	int	x = (int)SvIV(ST(1))
;
	int	y = (int)SvIV(ST(2))
;

	lcdPosition(fd, x, y);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Odroid__WiringPi_lcdPutchar); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Odroid__WiringPi_lcdPutchar)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "fd, data");
    {
	int	fd = (int)SvIV(ST(0))
;
	unsigned char	data = (unsigned char)SvUV(ST(1))
;

	lcdPutchar(fd, data);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Odroid__WiringPi_lcdPuts); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Odroid__WiringPi_lcdPuts)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "fd, string");
    {
	int	fd = (int)SvIV(ST(0))
;
	char *	string = (char *)SvPV_nolen(ST(1))
;

	lcdPuts(fd, string);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Odroid__WiringPi_lcdPrintf); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Odroid__WiringPi_lcdPrintf)
{
    dVAR; dXSARGS;
    if (items < 2)
       croak_xs_usage(cv,  "fd, message, ...");
    {
	int	fd = (int)SvIV(ST(0))
;
	char *	message = (char *)SvPV_nolen(ST(1))
;

	lcdPrintf(fd, message);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Odroid__WiringPi_lcdInit); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Odroid__WiringPi_lcdInit)
{
    dVAR; dXSARGS;
    if (items != 13)
       croak_xs_usage(cv,  "rows, cols, bits, rs, strb, d0, d1, d2, d3, d4, d5, d6, d7");
    {
	int	RETVAL;
	dXSTARG;
	int	rows = (int)SvIV(ST(0))
;
	int	cols = (int)SvIV(ST(1))
;
	int	bits = (int)SvIV(ST(2))
;
	int	rs = (int)SvIV(ST(3))
;
	int	strb = (int)SvIV(ST(4))
;
	int	d0 = (int)SvIV(ST(5))
;
	int	d1 = (int)SvIV(ST(6))
;
	int	d2 = (int)SvIV(ST(7))
;
	int	d3 = (int)SvIV(ST(8))
;
	int	d4 = (int)SvIV(ST(9))
;
	int	d5 = (int)SvIV(ST(10))
;
	int	d6 = (int)SvIV(ST(11))
;
	int	d7 = (int)SvIV(ST(12))
;

	RETVAL = lcdInit(rows, cols, bits, rs, strb, d0, d1, d2, d3, d4, d5, d6, d7);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Odroid__WiringPi_wiringPiSetup); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Odroid__WiringPi_wiringPiSetup)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	int	RETVAL;
	dXSTARG;

	RETVAL = wiringPiSetup();
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Odroid__WiringPi_wiringPiSetupSys); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Odroid__WiringPi_wiringPiSetupSys)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	int	RETVAL;
	dXSTARG;

	RETVAL = wiringPiSetupSys();
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Odroid__WiringPi_wiringPiSetupGpio); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Odroid__WiringPi_wiringPiSetupGpio)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	int	RETVAL;
	dXSTARG;

	RETVAL = wiringPiSetupGpio();
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Odroid__WiringPi_wiringPiSetupPhys); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Odroid__WiringPi_wiringPiSetupPhys)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	int	RETVAL;
	dXSTARG;

	RETVAL = wiringPiSetupPhys();
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Odroid__WiringPi_pinModeAlt); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Odroid__WiringPi_pinModeAlt)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "pin, mode");
    {
	int	pin = (int)SvIV(ST(0))
;
	int	mode = (int)SvIV(ST(1))
;

	pinModeAlt(pin, mode);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Odroid__WiringPi_pinMode); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Odroid__WiringPi_pinMode)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "pin, mode");
    {
	int	pin = (int)SvIV(ST(0))
;
	int	mode = (int)SvIV(ST(1))
;

	pinMode(pin, mode);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Odroid__WiringPi_pullUpDnControl); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Odroid__WiringPi_pullUpDnControl)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "pin, pud");
    {
	int	pin = (int)SvIV(ST(0))
;
	int	pud = (int)SvIV(ST(1))
;

	pullUpDnControl(pin, pud);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Odroid__WiringPi_digitalRead); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Odroid__WiringPi_digitalRead)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "pin");
    {
	int	RETVAL;
	dXSTARG;
	int	pin = (int)SvIV(ST(0))
;

	RETVAL = digitalRead(pin);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Odroid__WiringPi_digitalWrite); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Odroid__WiringPi_digitalWrite)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "pin, value");
    {
	int	pin = (int)SvIV(ST(0))
;
	int	value = (int)SvIV(ST(1))
;

	digitalWrite(pin, value);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Odroid__WiringPi_pwmWrite); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Odroid__WiringPi_pwmWrite)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "pin, value");
    {
	int	pin = (int)SvIV(ST(0))
;
	int	value = (int)SvIV(ST(1))
;

	pwmWrite(pin, value);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Odroid__WiringPi_analogRead); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Odroid__WiringPi_analogRead)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "pin");
    {
	int	RETVAL;
	dXSTARG;
	int	pin = (int)SvIV(ST(0))
;

	RETVAL = analogRead(pin);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Odroid__WiringPi_analogWrite); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Odroid__WiringPi_analogWrite)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "pin, value");
    {
	int	pin = (int)SvIV(ST(0))
;
	int	value = (int)SvIV(ST(1))
;

	analogWrite(pin, value);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Odroid__WiringPi_piBoardRev); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Odroid__WiringPi_piBoardRev)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	int	RETVAL;
	dXSTARG;

	RETVAL = piBoardRev();
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Odroid__WiringPi_wpiPinToGpio); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Odroid__WiringPi_wpiPinToGpio)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "wpiPin");
    {
	int	RETVAL;
	dXSTARG;
	int	wpiPin = (int)SvIV(ST(0))
;

	RETVAL = wpiPinToGpio(wpiPin);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Odroid__WiringPi_physPinToGpio); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Odroid__WiringPi_physPinToGpio)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "physPin");
    {
	int	RETVAL;
	dXSTARG;
	int	physPin = (int)SvIV(ST(0))
;

	RETVAL = physPinToGpio(physPin);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Odroid__WiringPi_setPadDrive); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Odroid__WiringPi_setPadDrive)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "group, value");
    {
	int	group = (int)SvIV(ST(0))
;
	int	value = (int)SvIV(ST(1))
;

	setPadDrive(group, value);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Odroid__WiringPi_getAlt); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Odroid__WiringPi_getAlt)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "pin");
    {
	int	RETVAL;
	dXSTARG;
	int	pin = (int)SvIV(ST(0))
;

	RETVAL = getAlt(pin);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Odroid__WiringPi_pwmToneWrite); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Odroid__WiringPi_pwmToneWrite)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "pin, freq");
    {
	int	pin = (int)SvIV(ST(0))
;
	int	freq = (int)SvIV(ST(1))
;

	pwmToneWrite(pin, freq);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Odroid__WiringPi_digitalWriteByte); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Odroid__WiringPi_digitalWriteByte)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "value");
    {
	int	value = (int)SvIV(ST(0))
;

	digitalWriteByte(value);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Odroid__WiringPi_pwmSetMode); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Odroid__WiringPi_pwmSetMode)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "mode");
    {
	int	mode = (int)SvIV(ST(0))
;

	pwmSetMode(mode);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Odroid__WiringPi_pwmSetRange); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Odroid__WiringPi_pwmSetRange)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "range");
    {
	unsigned int	range = (unsigned int)SvUV(ST(0))
;

	pwmSetRange(range);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Odroid__WiringPi_pwmSetClock); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Odroid__WiringPi_pwmSetClock)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "divisor");
    {
	int	divisor = (int)SvIV(ST(0))
;

	pwmSetClock(divisor);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Odroid__WiringPi_gpioClockSet); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Odroid__WiringPi_gpioClockSet)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "pin, freq");
    {
	int	pin = (int)SvIV(ST(0))
;
	int	freq = (int)SvIV(ST(1))
;

	gpioClockSet(pin, freq);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Odroid__WiringPi_waitForInterrupt); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Odroid__WiringPi_waitForInterrupt)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "pin, mS");
    {
	int	RETVAL;
	dXSTARG;
	int	pin = (int)SvIV(ST(0))
;
	int	mS = (int)SvIV(ST(1))
;

	RETVAL = waitForInterrupt(pin, mS);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Odroid__WiringPi_piLock); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Odroid__WiringPi_piLock)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "key");
    {
	int	key = (int)SvIV(ST(0))
;

	piLock(key);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Odroid__WiringPi_piUnlock); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Odroid__WiringPi_piUnlock)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "key");
    {
	int	key = (int)SvIV(ST(0))
;

	piUnlock(key);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Odroid__WiringPi_piHiPri); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Odroid__WiringPi_piHiPri)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "pri");
    {
	int	RETVAL;
	dXSTARG;
	int	pri = (int)SvIV(ST(0))
;

	RETVAL = piHiPri(pri);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Odroid__WiringPi_delay); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Odroid__WiringPi_delay)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "howLong");
    {
	unsigned int	howLong = (unsigned int)SvUV(ST(0))
;

	delay(howLong);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Odroid__WiringPi_delayMicroseconds); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Odroid__WiringPi_delayMicroseconds)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "howLong");
    {
	unsigned int	howLong = (unsigned int)SvUV(ST(0))
;

	delayMicroseconds(howLong);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Odroid__WiringPi_millis); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Odroid__WiringPi_millis)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	unsigned int	RETVAL;
	dXSTARG;

	RETVAL = millis();
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Odroid__WiringPi_micros); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Odroid__WiringPi_micros)
{
    dVAR; dXSARGS;
    if (items != 0)
       croak_xs_usage(cv,  "");
    {
	unsigned int	RETVAL;
	dXSTARG;

	RETVAL = micros();
	XSprePUSH; PUSHu((UV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Odroid__WiringPi_serialOpen); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Odroid__WiringPi_serialOpen)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "device, baud");
    {
	int	RETVAL;
	dXSTARG;
	const char *	device = (const char *)SvPV_nolen(ST(0))
;
	int	baud = (int)SvIV(ST(1))
;

	RETVAL = serialOpen(device, baud);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Odroid__WiringPi_serialClose); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Odroid__WiringPi_serialClose)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "fd");
    {
	int	fd = (int)SvIV(ST(0))
;

	serialClose(fd);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Odroid__WiringPi_serialFlush); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Odroid__WiringPi_serialFlush)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "fd");
    {
	int	fd = (int)SvIV(ST(0))
;

	serialFlush(fd);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Odroid__WiringPi_serialPutchar); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Odroid__WiringPi_serialPutchar)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "fd, c");
    {
	int	fd = (int)SvIV(ST(0))
;
	char	c = (char)*SvPV_nolen(ST(1))
;

	serialPutchar(fd, c);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Odroid__WiringPi_serialPuts); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Odroid__WiringPi_serialPuts)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "fd, s");
    {
	int	fd = (int)SvIV(ST(0))
;
	const char *	s = (const char *)SvPV_nolen(ST(1))
;

	serialPuts(fd, s);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Odroid__WiringPi_serialPrintf); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Odroid__WiringPi_serialPrintf)
{
    dVAR; dXSARGS;
    if (items < 2)
       croak_xs_usage(cv,  "fd, message, ...");
    {
	int	fd = (int)SvIV(ST(0))
;
	const char *	message = (const char *)SvPV_nolen(ST(1))
;

	serialPrintf(fd, message);
    }
    XSRETURN_EMPTY;
}


XS_EUPXS(XS_Odroid__WiringPi_serialDataAvail); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Odroid__WiringPi_serialDataAvail)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "fd");
    {
	int	RETVAL;
	dXSTARG;
	int	fd = (int)SvIV(ST(0))
;

	RETVAL = serialDataAvail(fd);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Odroid__WiringPi_serialGetchar); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Odroid__WiringPi_serialGetchar)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "fd");
    {
	int	RETVAL;
	dXSTARG;
	int	fd = (int)SvIV(ST(0))
;

	RETVAL = serialGetchar(fd);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Odroid__WiringPi_wiringPiI2CRead); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Odroid__WiringPi_wiringPiI2CRead)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "fd");
    {
	int	RETVAL;
	dXSTARG;
	int	fd = (int)SvIV(ST(0))
;

	RETVAL = wiringPiI2CRead(fd);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Odroid__WiringPi_wiringPiI2CReadReg8); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Odroid__WiringPi_wiringPiI2CReadReg8)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "fd, reg");
    {
	int	RETVAL;
	dXSTARG;
	int	fd = (int)SvIV(ST(0))
;
	int	reg = (int)SvIV(ST(1))
;

	RETVAL = wiringPiI2CReadReg8(fd, reg);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Odroid__WiringPi_wiringPiI2CReadReg16); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Odroid__WiringPi_wiringPiI2CReadReg16)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "fd, reg");
    {
	int	RETVAL;
	dXSTARG;
	int	fd = (int)SvIV(ST(0))
;
	int	reg = (int)SvIV(ST(1))
;

	RETVAL = wiringPiI2CReadReg16(fd, reg);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Odroid__WiringPi_wiringPiI2CWrite); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Odroid__WiringPi_wiringPiI2CWrite)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "fd, data");
    {
	int	RETVAL;
	dXSTARG;
	int	fd = (int)SvIV(ST(0))
;
	int	data = (int)SvIV(ST(1))
;

	RETVAL = wiringPiI2CWrite(fd, data);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Odroid__WiringPi_wiringPiI2CWriteReg8); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Odroid__WiringPi_wiringPiI2CWriteReg8)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "fd, reg, data");
    {
	int	RETVAL;
	dXSTARG;
	int	fd = (int)SvIV(ST(0))
;
	int	reg = (int)SvIV(ST(1))
;
	int	data = (int)SvIV(ST(2))
;

	RETVAL = wiringPiI2CWriteReg8(fd, reg, data);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Odroid__WiringPi_wiringPiI2CWriteReg16); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Odroid__WiringPi_wiringPiI2CWriteReg16)
{
    dVAR; dXSARGS;
    if (items != 3)
       croak_xs_usage(cv,  "fd, reg, data");
    {
	int	RETVAL;
	dXSTARG;
	int	fd = (int)SvIV(ST(0))
;
	int	reg = (int)SvIV(ST(1))
;
	int	data = (int)SvIV(ST(2))
;

	RETVAL = wiringPiI2CWriteReg16(fd, reg, data);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Odroid__WiringPi_wiringPiI2CSetupInterface); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Odroid__WiringPi_wiringPiI2CSetupInterface)
{
    dVAR; dXSARGS;
    if (items != 2)
       croak_xs_usage(cv,  "device, devId");
    {
	int	RETVAL;
	dXSTARG;
	const char *	device = (const char *)SvPV_nolen(ST(0))
;
	int	devId = (int)SvIV(ST(1))
;

	RETVAL = wiringPiI2CSetupInterface(device, devId);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}


XS_EUPXS(XS_Odroid__WiringPi_wiringPiI2CSetup); /* prototype to pass -Wmissing-prototypes */
XS_EUPXS(XS_Odroid__WiringPi_wiringPiI2CSetup)
{
    dVAR; dXSARGS;
    if (items != 1)
       croak_xs_usage(cv,  "devId");
    {
	int	RETVAL;
	dXSTARG;
	int	devId = (int)SvIV(ST(0))
;

	RETVAL = wiringPiI2CSetup(devId);
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

#ifdef __cplusplus
extern "C"
#endif
XS_EXTERNAL(boot_Odroid__WiringPi); /* prototype to pass -Wmissing-prototypes */
XS_EXTERNAL(boot_Odroid__WiringPi)
{
    dVAR; dXSARGS;
#if (PERL_REVISION == 5 && PERL_VERSION < 9)
    char* file = __FILE__;
#else
    const char* file = __FILE__;
#endif

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
#ifdef XS_APIVERSION_BOOTCHECK
    XS_APIVERSION_BOOTCHECK;
#endif
    XS_VERSION_BOOTCHECK;

        newXS("Odroid::WiringPi::lcdHome", XS_Odroid__WiringPi_lcdHome, file);
        newXS("Odroid::WiringPi::lcdClear", XS_Odroid__WiringPi_lcdClear, file);
        newXS("Odroid::WiringPi::lcdDisplay", XS_Odroid__WiringPi_lcdDisplay, file);
        newXS("Odroid::WiringPi::lcdCursor", XS_Odroid__WiringPi_lcdCursor, file);
        newXS("Odroid::WiringPi::lcdCursorBlink", XS_Odroid__WiringPi_lcdCursorBlink, file);
        newXS("Odroid::WiringPi::lcdSendCommand", XS_Odroid__WiringPi_lcdSendCommand, file);
        newXS("Odroid::WiringPi::lcdPosition", XS_Odroid__WiringPi_lcdPosition, file);
        newXS("Odroid::WiringPi::lcdPutchar", XS_Odroid__WiringPi_lcdPutchar, file);
        newXS("Odroid::WiringPi::lcdPuts", XS_Odroid__WiringPi_lcdPuts, file);
        newXS("Odroid::WiringPi::lcdPrintf", XS_Odroid__WiringPi_lcdPrintf, file);
        newXS("Odroid::WiringPi::lcdInit", XS_Odroid__WiringPi_lcdInit, file);
        newXS("Odroid::WiringPi::wiringPiSetup", XS_Odroid__WiringPi_wiringPiSetup, file);
        newXS("Odroid::WiringPi::wiringPiSetupSys", XS_Odroid__WiringPi_wiringPiSetupSys, file);
        newXS("Odroid::WiringPi::wiringPiSetupGpio", XS_Odroid__WiringPi_wiringPiSetupGpio, file);
        newXS("Odroid::WiringPi::wiringPiSetupPhys", XS_Odroid__WiringPi_wiringPiSetupPhys, file);
        newXS("Odroid::WiringPi::pinModeAlt", XS_Odroid__WiringPi_pinModeAlt, file);
        newXS("Odroid::WiringPi::pinMode", XS_Odroid__WiringPi_pinMode, file);
        newXS("Odroid::WiringPi::pullUpDnControl", XS_Odroid__WiringPi_pullUpDnControl, file);
        newXS("Odroid::WiringPi::digitalRead", XS_Odroid__WiringPi_digitalRead, file);
        newXS("Odroid::WiringPi::digitalWrite", XS_Odroid__WiringPi_digitalWrite, file);
        newXS("Odroid::WiringPi::pwmWrite", XS_Odroid__WiringPi_pwmWrite, file);
        newXS("Odroid::WiringPi::analogRead", XS_Odroid__WiringPi_analogRead, file);
        newXS("Odroid::WiringPi::analogWrite", XS_Odroid__WiringPi_analogWrite, file);
        newXS("Odroid::WiringPi::piBoardRev", XS_Odroid__WiringPi_piBoardRev, file);
        newXS("Odroid::WiringPi::wpiPinToGpio", XS_Odroid__WiringPi_wpiPinToGpio, file);
        newXS("Odroid::WiringPi::physPinToGpio", XS_Odroid__WiringPi_physPinToGpio, file);
        newXS("Odroid::WiringPi::setPadDrive", XS_Odroid__WiringPi_setPadDrive, file);
        newXS("Odroid::WiringPi::getAlt", XS_Odroid__WiringPi_getAlt, file);
        newXS("Odroid::WiringPi::pwmToneWrite", XS_Odroid__WiringPi_pwmToneWrite, file);
        newXS("Odroid::WiringPi::digitalWriteByte", XS_Odroid__WiringPi_digitalWriteByte, file);
        newXS("Odroid::WiringPi::pwmSetMode", XS_Odroid__WiringPi_pwmSetMode, file);
        newXS("Odroid::WiringPi::pwmSetRange", XS_Odroid__WiringPi_pwmSetRange, file);
        newXS("Odroid::WiringPi::pwmSetClock", XS_Odroid__WiringPi_pwmSetClock, file);
        newXS("Odroid::WiringPi::gpioClockSet", XS_Odroid__WiringPi_gpioClockSet, file);
        newXS("Odroid::WiringPi::waitForInterrupt", XS_Odroid__WiringPi_waitForInterrupt, file);
        newXS("Odroid::WiringPi::piLock", XS_Odroid__WiringPi_piLock, file);
        newXS("Odroid::WiringPi::piUnlock", XS_Odroid__WiringPi_piUnlock, file);
        newXS("Odroid::WiringPi::piHiPri", XS_Odroid__WiringPi_piHiPri, file);
        newXS("Odroid::WiringPi::delay", XS_Odroid__WiringPi_delay, file);
        newXS("Odroid::WiringPi::delayMicroseconds", XS_Odroid__WiringPi_delayMicroseconds, file);
        newXS("Odroid::WiringPi::millis", XS_Odroid__WiringPi_millis, file);
        newXS("Odroid::WiringPi::micros", XS_Odroid__WiringPi_micros, file);
        newXS("Odroid::WiringPi::serialOpen", XS_Odroid__WiringPi_serialOpen, file);
        newXS("Odroid::WiringPi::serialClose", XS_Odroid__WiringPi_serialClose, file);
        newXS("Odroid::WiringPi::serialFlush", XS_Odroid__WiringPi_serialFlush, file);
        newXS("Odroid::WiringPi::serialPutchar", XS_Odroid__WiringPi_serialPutchar, file);
        newXS("Odroid::WiringPi::serialPuts", XS_Odroid__WiringPi_serialPuts, file);
        newXS("Odroid::WiringPi::serialPrintf", XS_Odroid__WiringPi_serialPrintf, file);
        newXS("Odroid::WiringPi::serialDataAvail", XS_Odroid__WiringPi_serialDataAvail, file);
        newXS("Odroid::WiringPi::serialGetchar", XS_Odroid__WiringPi_serialGetchar, file);
        newXS("Odroid::WiringPi::wiringPiI2CRead", XS_Odroid__WiringPi_wiringPiI2CRead, file);
        newXS("Odroid::WiringPi::wiringPiI2CReadReg8", XS_Odroid__WiringPi_wiringPiI2CReadReg8, file);
        newXS("Odroid::WiringPi::wiringPiI2CReadReg16", XS_Odroid__WiringPi_wiringPiI2CReadReg16, file);
        newXS("Odroid::WiringPi::wiringPiI2CWrite", XS_Odroid__WiringPi_wiringPiI2CWrite, file);
        newXS("Odroid::WiringPi::wiringPiI2CWriteReg8", XS_Odroid__WiringPi_wiringPiI2CWriteReg8, file);
        newXS("Odroid::WiringPi::wiringPiI2CWriteReg16", XS_Odroid__WiringPi_wiringPiI2CWriteReg16, file);
        newXS("Odroid::WiringPi::wiringPiI2CSetupInterface", XS_Odroid__WiringPi_wiringPiI2CSetupInterface, file);
        newXS("Odroid::WiringPi::wiringPiI2CSetup", XS_Odroid__WiringPi_wiringPiI2CSetup, file);
#if (PERL_REVISION == 5 && PERL_VERSION >= 9)
  if (PL_unitcheckav)
       call_list(PL_scopestack_ix, PL_unitcheckav);
#endif
    XSRETURN_YES;
}

